from django.core.management.base import BaseCommand
from blog.models import Tag


class Command(BaseCommand):

    def handle(self, *args, **kwargs):
        tags = [
            ("python", "🐍 Python"),
            ("javascript", "🟨 JavaScript"),
            ("typescript", "🔷 TypeScript"),
            ("java", "☕ Java"),
            ("kotlin", "🟣 Kotlin"),
            ("c", "🔵 C"),
            ("cpp", "⚙️ C++"),
            ("csharp", "💠 C#"),
            ("go", "🐹 Go"),
            ("rust", "🦀 Rust"),
            ("php", "🐘 PHP"),
            ("dart", "🎯 Dart"),
            ("swift", "🍎 Swift"),
            ("html", "🌐 HTML"),
            ("css", "🎨 CSS"),
            ("bootstrap", "🅱️ Bootstrap"),
            ("tailwind", "💨 Tailwind CSS"),
            ("react", "⚛️ React"),
            ("vue", "💚 Vue.js"),
            ("angular", "🅰️ Angular"),
            ("nextjs", "▲ Next.js"),
            ("nuxtjs", "💚 Nuxt.js"),
            ("django", "🟢 Django"),
            ("drf", "🌿 Django REST Framework"),
            ("flask", "🧪 Flask"),
            ("fastapi", "⚡ FastAPI"),
            ("express", "🚂 Express.js"),
            ("laravel", "❤️ Laravel"),
            ("aspnet", "🔷 ASP.NET"),
            ("springboot", "🍃 Spring Boot"),
            ("nodejs", "🟩 Node.js"),
            ("postgresql", "🐘 PostgreSQL"),
            ("mysql", "🐬 MySQL"),
            ("sqlite", "📦 SQLite"),
            ("mongodb", "🍃 MongoDB"),
            ("redis", "🔴 Redis"),
            ("mariadb", "🦭 MariaDB"),
            ("flutter", "💙 Flutter"),
            ("android", "🤖 Android"),
            ("ios", "📱 iOS"),
            ("reactnative", "📲 React Native"),
            ("git", "🔀 Git"),
            ("github", "🐙 GitHub"),
            ("gitlab", "🦊 GitLab"),
            ("docker", "🐳 Docker"),
            ("kubernetes", "☸️ Kubernetes"),
            ("linux", "🐧 Linux"),
            ("nginx", "🌐 Nginx"),
            ("cicd", "🚀 CI/CD"),
            ("restapi", "🔌 REST API"),
            ("graphql", "🔺 GraphQL"),
            ("ai", "🤖 AI"),
            ("machinelearning", "🧠 Machine Learning"),
            ("deeplearning", "🌊 Deep Learning"),
            ("llm", "💬 LLM"),
            ("promptengineering", "✨ Prompt Engineering"),
            ("openaiapi", "🟢 OpenAI API"),
            ("tensorflow", "🧡 TensorFlow"),
            ("pytorch", "🔥 PyTorch"),
            ("cybersecurity", "🛡️ Cyber Security"),
            ("owasp", "🔒 OWASP"),
            ("authentication", "🔑 Authentication"),
            ("jwt", "🎫 JWT"),
            ("oauth", "🔐 OAuth"),
            ("algorithm", "📐 Algorithm"),
            ("datastructure", "🧩 Data Structure"),
            ("oop", "🏗️ OOP"),
            ("designpattern", "🎨 Design Pattern"),
            ("cleancode", "🧹 Clean Code"),
            ("refactoring", "♻️ Refactoring"),
            ("testing", "🧪 Testing"),
            ("unittest", "✅ Unit Test"),
            ("performance", "⚡ Performance"),
            ("aws", "☁️ AWS"),
            ("azure", "🔷 Azure"),
            ("gcp", "🌈 Google Cloud"),
            ("gamedev", "🎮 Game Development"),
            ("webdev", "🌍 Web Development"),
            ("desktopapp", "🖥️ Desktop App"),
            ("api", "🔗 API"),
            ("opensource", "❤️ Open Source"),
        ]

        for id, name in tags:
            Tag.objects.get_or_create(name=name)

        self.stdout.write(
            self.style.SUCCESS("Tags created")
        )
