# Generated by Django 5.2.8 on 2026-06-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower_users',
            new_name='followings',
        ),
    ]
