# Generated by Django 5.2.8 on 2026-06-18 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_total_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(max_length=1500, verbose_name='text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('read', models.BooleanField(default=False)),
                ('admin_wrote', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
