# Generated by Django 5.2.8 on 2026-06-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_localticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
