# Generated by Django 5.2.8 on 2026-06-24 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_commentmodel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('middle', 'متوسط'), ('professional', 'حرفه ای')], default='beginner')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=250, verbose_name='مهارت')),
                ('confirmed', models.BooleanField(default=False, verbose_name='تایید شده بودن')),
            ],
        ),
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveIndex(
            model_name='commentmodel',
            name='blog_commen_created_0e3a0f_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.AddField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='github_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_skill',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='main_skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.TextField(blank=True, null=True, verbose_name='پروژه و نمونه کار(حتی کوچیک)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tel_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tellegram_id'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WIL', 'چیزی که یاد گرفتم'), ('WIC', 'پروزه یا نمونه کار ساختم'), ('SFT', 'دتبال هم تیمی میگزدم'), ('IHQ', 'سوال درام')], default='another'),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['-created'], name='blog_commen_created_983d6e_idx'),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='blog.level', verbose_name='سطح'),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
