# Generated by Django 5.2.8 on 2026-06-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_level_skill_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='تکنولوژی')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'مبتدی'), ('middle', 'متوسط'), ('professional', 'حرفه ای')], default='beginner', verbose_name='سطح'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='user',
            name='ostan',
            field=models.CharField(blank=True, choices=[('azarbaijan_sharghi', 'آذربایجان شرقی'), ('azarbaijan_gharbi', 'آذربایجان غربی'), ('ardabil', 'اردبیل'), ('esfahan', 'اصفهان'), ('alborz', 'البرز'), ('ilam', 'ایلام'), ('bushehr', 'بوشهر'), ('tehran', 'تهران'), ('chaharmahal_bakhtiari', 'چهارمحال و بختیاری'), ('khorasan_jonoobi', 'خراسان جنوبی'), ('khorasan_razavi', 'خراسان رضوی'), ('khorasan_shomali', 'خراسان شمالی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan_baluchestan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kordestan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiluyeh_boyerahmad', 'کهگیلویه و بویراحمد'), ('golestan', 'گلستان'), ('gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamadan', 'همدان'), ('yazd', 'یزد')], max_length=50, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WIL', 'چیزی که یاد گرفتم'), ('WIC', 'پروزه یا نمونه کار ساختم'), ('SFT', 'دتبال هم تیمی میگزدم'), ('IHQ', 'سوال درام')], default='WIL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='github_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram_id'),
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'تکمیل شده'), ('ongoing', 'در حال توسعه')], max_length=20)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='blog.post')),
                ('technologies', models.ManyToManyField(blank=True, to='blog.technology')),
            ],
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
