# Generated by Django 5.2.8 on 2026-07-01 04:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_alter_skill_skill_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_file',
            field=models.ImageField(upload_to=blog.models.ImagePost.image_directory),
        ),
    ]
