# Generated by Django 5.2.8 on 2026-07-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_imagepost_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_description', models.CharField()),
                ('text_name', models.CharField()),
            ],
        ),
    ]
