# Generated by Django 5.2.8 on 2026-07-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notif',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'در حال بررسی'), ('PB', 'منتشر شده'), ('RJ', 'رد شده')], default='PB', max_length=2),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_name',
            field=models.CharField(unique=True),
        ),
    ]
