# Generated by Django 5.2.8 on 2026-07-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL),
        ),
    ]
