# Generated by Django 5.2.8 on 2026-07-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_team_teamrequest_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(default='___', max_length=50, verbose_name='تکنولوژی'),
        ),
    ]
