# Generated by Django 5.2.8 on 2026-07-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_technology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_saves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
