# Generated by Django 5.2.8 on 2026-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_total_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', '(junior)مبتدی'), ('middle', '(mid-level)متوسط'), ('professional', '(senior)حرفه ای')], default='beginner', verbose_name='سطح'),
        ),
    ]
