# Generated by Django 5.2.8 on 2026-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_commentmodel_helpful_user_verify_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('beginner', '(junior)مبتدی'), ('middle', '(mid-level)متوسط'), ('professional', '(senior)حرفه ای')], default='beginner', verbose_name='سطح'),
        ),
    ]
