# Generated by Django 5.2.8 on 2026-07-29 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 29, 14, 40, 57, 479445, tzinfo=datetime.timezone.utc)),
        ),
    ]
