# Generated by Django 5.2.8 on 2026-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='github_id'),
        ),
    ]
